apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: sneakershop
  labels:
    k8s-app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: gateway
  template:
    metadata:
      labels:
        k8s-app: gateway
    spec:
      containers:
        - name: gateway
          image: quangghuyyyyy/gateway:latest # Thay bằng tên image Gateway của bạn trên Docker Hub
          ports:
            - containerPort: 80
