apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: sneakershop
spec:
  type: NodePort
  ports:
    - port: 80       # Port mà Gateway lắng nghe trong cluster
      targetPort: 80 # Port mà container Gateway đang chạy
      nodePort: 30008 # Port để truy cập từ bên ngoài
  selector:
    k8s-app: gateway
