apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: sneakershop
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001 # Port để truy cập từ bên ngoài
  selector:
    k8s-app: auth
