apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock
  namespace: sneakershop
  labels:
    k8s-app: stock
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: stock
  template:
    metadata:
      name: stock
      labels:
        k8s-app: stock
    spec:
      containers:
        - name: stock
          image: quangghuyyyyy/stockservice:latest
          securityContext:
            privileged: false
