apiVersion: v1
kind: Service
metadata:
  name: shipping
  namespace: sneakershop
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30005
  selector:
    k8s-app: shipping
