apiVersion: v1
kind: Service
metadata:
  name: invoice
  namespace: sneakershop
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30002
  selector:
    k8s-app: invoice
